package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"testtask/internal/server/graph/generated"
	"testtask/internal/server/graph/model"
)

// NetworkInterfaces is the resolver for the networkInterfaces field.
func (r *queryResolver) NetworkInterfaces(ctx context.Context) ([]*model.NetInterface, error) {
	interfaces := r.StatsService.GetInterfaces()
	var result []*model.NetInterface
	for _, iface := range interfaces {
		config := &model.InterfaceConfig{
			HardwareAddr: &iface.Config.HardwareAddr,
			Mtu:          &iface.Config.MTU,
			Flags:        iface.Config.Flags,
			Addrs:        iface.Config.Addrs,
		}
		result = append(result, &model.NetInterface{
			Name:            iface.Name,
			Config:          config,
			LinkUp:          iface.LinkUp,
			PacketsSent:     int(iface.PacketsSent),
			PacketsReceived: int(iface.PacketsReceived),
			BytesSent:       int(iface.BytesSent),
			BytesReceived:   int(iface.BytesReceived),
			SpeedSent:       iface.SpeedSent,
			SpeedReceived:   iface.SpeedReceived,
		})
	}
	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	type Resolver struct {
	StatsService *stats.Service
}
*/
