// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NetInterface struct {
	Name            string  `json:"name"`
	Config          *string `json:"config,omitempty"`
	LinkUp          bool    `json:"linkUp"`
	PacketsSent     int     `json:"packetsSent"`
	PacketsReceived int     `json:"packetsReceived"`
	BytesSent       int     `json:"bytesSent"`
	BytesReceived   int     `json:"bytesReceived"`
	SpeedSent       float64 `json:"speedSent"`
	SpeedReceived   float64 `json:"speedReceived"`
}

type Query struct {
}
